# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
#

guard 'rake', :task => 'test' do
	watch(%r{^src/main/.*$})
	watch(%r{^src/test/.*/content\.txt$})
	watch(%r{^setup/setup.*\.sql$})
end

